matrix:
  include:
  - compiler: gcc
    env: CC=gcc CXX=g++
    os: linux
  - compiler: clang
    env: CC=clang CXX=clang++
    os: linux
  - os: osx
  - addons:
      apt:
        packages:
        - g++-5
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-5 g++-5 std=c++11
    os: linux
  - addons:
      apt:
        packages:
        - g++-5
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-5 g++-5 std=c++14
    os: linux
  - addons:
      apt:
        packages:
        - g++-5
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-5 g++-5 std=c++17
    os: linux
  - addons:
      apt:
        packages:
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-6 g++-6 std=c++11
    os: linux
  - addons:
      apt:
        packages:
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-6 g++-6 std=c++14
    os: linux
  - addons:
      apt:
        packages:
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-6 g++-6 std=c++17
    os: linux
  - addons:
      apt:
        packages:
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-7 g++-7 std=c++11
    os: linux
  - addons:
      apt:
        packages:
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-7 g++-7 std=c++14
    os: linux
  - addons:
      apt:
        packages:
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-7 g++-7 std=c++17
    os: linux
  - addons:
      apt:
        packages:
        - g++-8
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-8 g++-8 std=c++11
    os: linux
  - addons:
      apt:
        packages:
        - g++-8
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-8 g++-8 std=c++14
    os: linux
  - addons:
      apt:
        packages:
        - g++-8
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-8 g++-8 std=c++17
    os: linux
  - addons:
      apt:
        packages:
        - g++-8
        sources:
        - ubuntu-toolchain-r-test
    compiler: gcc
    env: CC=gcc-8 g++-8 std=c++2a
    os: linux
  - addons:
      apt:
        packages:
        - clang-4.0
        sources:
        - llvm-toolchain-trusty-4.0
    compiler: clang
    env: CC=clang-4.0 clang++-4.0 std=c++11
    os: linux
  - addons:
      apt:
        packages:
        - clang-4.0
        sources:
        - llvm-toolchain-trusty-4.0
    compiler: clang
    env: CC=clang-4.0 clang++-4.0 std=c++14
    os: linux
  - addons:
      apt:
        packages:
        - clang-4.0
        sources:
        - llvm-toolchain-trusty-4.0
    compiler: clang
    env: CC=clang-4.0 clang++-4.0 std=c++17
    os: linux
  - addons:
      apt:
        packages:
        - clang-5.0
        sources:
        - llvm-toolchain-trusty-5.0
    compiler: clang
    env: CC=clang-5.0 clang++-5.0 std=c++11
    os: linux
  - addons:
      apt:
        packages:
        - clang-5.0
        sources:
        - llvm-toolchain-trusty-5.0
    compiler: clang
    env: CC=clang-5.0 clang++-5.0 std=c++14
    os: linux
  - addons:
      apt:
        packages:
        - clang-5.0
        sources:
        - llvm-toolchain-trusty-5.0
    compiler: clang
    env: CC=clang-5.0 clang++-5.0 std=c++17
    os: linux
  - addons:
      apt:
        packages:
        - clang-5.0
        sources:
        - llvm-toolchain-trusty-5.0
    compiler: clang
    env: CC=clang-5.0 clang++-5.0 std=c++2a
    os: linux

dist: trusty
sudo: required

before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libboost-dev; fi
- git submodule update --init --recursive

script:
- mkdir build
- cd build
- STD=${std} cmake ..
- make
- ctest --output-on-failure
