language: generic
dist: trusty

matrix:
  include:
    - compiler: gcc
      os: linux
      env:
        - CC=gcc
        - CXX=g++
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC=gcc-5
        - CXX=g++-5
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6
        - CXX=g++-6
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
    - compiler: clang
      os: linux
      env:
        - CC=clang
        - CXX=clang++
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - CC=clang-4.0
        - CXX=clang++-4.0
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7.0
          packages:
            - clang-7.0
      env:
        - CC=clang-7.0
        - CXX=clang++-7.0
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-8.0
          packages:
            - clang-8.0
      env:
        - CC=clang-8.0
        - CXX=clang++-8.0
    - os: osx

sudo: required
dist: trusty

before_install:
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
