language: generic
dist: trusty

matrix:
  include:
    - compiler: gcc
      os: linux
      env:
        - CC=gcc CXX=g++ std=c++11
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC=gcc-5 CXX=g++-5 std=c++11
        - CC=gcc-5 CXX=g++-5 std=c++14
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6 CXX=g++-6 std=c++11
        - CC=gcc-6 CXX=g++-6 std=c++14
        - CC=gcc-6 CXX=g++-6 std=c++17
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7 CXX=g++-7 std=c++11
        - CC=gcc-7 CXX=g++-7 std=c++14
        - CC=gcc-7 CXX=g++-7 std=c++17
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - CC=gcc-8 CXX=g++-8 std=c++11
        - CC=gcc-8 CXX=g++-8 std=c++14
        - CC=gcc-8 CXX=g++-8 std=c++17
        - CC=gcc-8 CXX=g++-8 std=c++2a
    - compiler: clang
      os: linux
      env:
        - CC=clang CXX=clang++ std=c++11
        - CC=clang CXX=clang++ std=c++14
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - CC=clang CXX=clang++ std=c++11
        - CC=clang CXX=clang++ std=c++14
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - CC=clang CXX=clang++ std=c++11
        - CC=clang CXX=clang++ std=c++14
        - CC=clang CXX=clang++ std=c++17
        - CC=clang CXX=clang++ std=c++2a
#    - compiler: clang
#      os: linux
#      addons:
#        apt:
#          sources:
#            - llvm-toolchain-trusty-6.0
#          packages:
#            - clang-6.0
#      env:
#        - CC=clang-6.0
#        - CXX=clang++-6.0
    - os: osx

sudo: required
dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libboost-dev; fi
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure
