environment:
  matrix:
    - GENERATOR_NAME: "Visual Studio 12 2013"
    - GENERATOR_NAME: "Visual Studio 12 2013 Win64"
    - GENERATOR_NAME: "Visual Studio 14 2015"
    - GENERATOR_NAME: "Visual Studio 14 2015 Win64"

platform: x64
configuration: Release

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - ctest
