environment:
  matrix:
#    - GENERATOR_NAME: "MinGW Makefiles"
#      MINGW_DIR: "C:\\MinGW"

#    - GENERATOR_NAME: "MinGW Makefiles"
#      MINGW_DIR: "C:\\mingw-w64\\i686-6.3.0-posix-dwarf-rt_v5-rev1"

#    - GENERATOR_NAME: "MinGW Makefiles"
#      MINGW_DIR: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1"

    - GENERATOR_NAME: "Visual Studio 12 2013"
      BOOST_VERSION: 1_58_0

    - GENERATOR_NAME: "Visual Studio 12 2013 Win64"
      BOOST_VERSION: 1_58_0

    - GENERATOR_NAME: "Visual Studio 14 2015"
      BOOST_VERSION: 1_63_0

    - GENERATOR_NAME: "Visual Studio 14 2015 Win64"
      BOOST_VERSION: 1_63_0

    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      GENERATOR_NAME: "Visual Studio 15 2017"
      BOOST_VERSION: 1_69_0

    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
      GENERATOR_NAME: "Visual Studio 15 2017 Win64"
      BOOST_VERSION: 1_69_0

platform: x64
configuration: Release

install:
- git submodule update --init --recursive

build_script:

# Set up MinGW paths if needed
# Rename sh.exe as sh.exe in PATH interferes with MinGW
- if defined MINGW_DIR cd testing/unit-tests/googletest
- if defined MINGW_DIR git apply ../../../patches/gtest_mingw.patch
- if defined MINGW_DIR cd ../../..
- if defined MINGW_DIR rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
- if defined MINGW_DIR set "PATH=%MINGW_DIR%\bin;%PATH%"

- mkdir build
- cd build
- if defined MINGW_DIR cmake -G "%GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=Release ..
- if not defined MINGW_DIR cmake -G "%GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING -DBOOST_ROOT="C:/Libraries/boost_%BOOST_VERSION%" ..
- cmake --build . --config "Release"
- ctest
